suggested change in the connection-test.js file
HackYourFuture/databases pull request #446
Opened 2020-10-13 20:48 UTC by FatmaHameed

Hi in HYF. I suggest adding the port number in the connection-test.js file. It could be optional in case the first code did not work for students as what happened to me. I always got access denied error before adding it. I hope it helps

2020-10-13 21:54 UTC, unmeshvrije requested changes
Please remove package.json from the commit.
And make the port number change optional.

2020-10-13 21:54 UTC, unmeshvrije commented on Week1/connection-test.js
> +  port : 3307 // this line was not added before to the file. I added according to my selected port. It could be changed according to your selected port
The default port is 3306 and by default used by [mysqljs](https://github.com/mysqljs/mysql/blob/3430c513d6b0ca279fb7c79b210c9301e9315658/Readme.md)

I would suggest adding the port option as the comment and writing something like
`// port : xxxx // Uncomment this line and replace xxxx with the selected port number if you are not using default 3306`

2020-10-15 11:28 UTC, FatmaHameed commented
Thank you @unmeshvrije for considering this. I changed the addition as per your request

2020-10-20 19:15 UTC, FatmaHameed commented
Hi @unmeshvrije , After trying to create the databases' dumbs, I realized that adding the port number is not a sustainable solution. I will try to explain how to fix the issues permanently and push it for future students because I do not want anyone to go through the same problem and waste time solving it as I did. Special thanks to Serafima because she spent a long time with me to solve it.

2020-10-20 19:34 UTC, unmeshvrije approved these changes

2020-10-20 19:34 UTC, merged